services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html:ro
      - nginx_logs:/var/log/nginx
    restart: always
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    networks:
      - inception-net

  wordpress:
    build: ./wordpress
    expose:
      - "9000"
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html
      - wp_logs:/var/log/php
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_EDITOR_USER: ${WP_EDITOR_USER}
      WP_EDITOR_PASSWORD: ${WP_EDITOR_PASSWORD}
      WP_EDITOR_EMAIL: ${WP_EDITOR_EMAIL}
    networks:
      - inception-net

  mariadb:
    build: ./mariadb
    expose:
      - "3306"
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - db_logs:/var/log/mysql
    networks:
      - inception-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: "30s" # 立ち上がるのに、30秒かかりそう
      retries: 30
      timeout: "5s"
      interval: "1s"

networks:
  inception-net:

volumes:
  nginx_logs:
    driver: local
    driver_opts:
      o: bind
      device: ${DATA_ROOT_PATH}/nginx/logs
      type: none
  wp_data:
    driver: local
    driver_opts:
      o: bind
      device: ${DATA_ROOT_PATH}/wordpress/data
      type: none
  wp_logs:
    driver: local
    driver_opts:
      o: bind
      device: ${DATA_ROOT_PATH}/wordpress/logs
      type: none
  db_data:
    driver: local
    driver_opts:
      o: bind
      device: ${DATA_ROOT_PATH}/mariadb/data
      type: none
  db_logs:
    driver: local
    driver_opts:
      o: bind
      device: ${DATA_ROOT_PATH}/mariadb/logs
      type: none
